### ISSUE TITLE
It would help if you could reference core Papers/other read & used in creation of this

### ISSUE THREAD

**Issue by abhishekkr** [wangyi-fudan/wyGPT#1]
Hi,

Thanks for the hard work you've put into this.

If you could, I'm interested in the Paper (any other material) references you have used to get this done.

**Comment by wangyi-fudan** [comment]
hi, 
it is close to this paper:
https://arxiv.org/abs/2307.14995
There are many differences as it is developed by myself independently, and my solution is better due to thousands of trials.
For my paper... I prefer code rather than paper. Maybe my PhD will be interested in writing it one day.

**Comment by abhishekkr** [comment]
Thanks, I hope to read your paper soon.
